### ISSUE TITLE
read-only state on the select component

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#307] opened 2023-04-18 13:12 UTC
### Description

We lack a read-only state on the select component. As with textfields there are cases where you want to have the data inside the field visible, but you dont want the user to be able to edit it. 

## Tasks
- [ ] Design read-only states

### Additional Information

This is needed by Altinn 3 Apps

**Comment by Febakke** [comment] 2023-04-27 08:35
We think it is a better pattern to use text to show read-only values, we will wait untill Altinn 3 has decided how they should solve this issue before we implement read-only states. Read more: [Aksel: deaktiverte tilstander](https://aksel.nav.no/god-praksis/artikler/deaktiverte-tilstander?tema=skjemaer)

[Altinn 3 issue](https://github.com/Altinn/app-frontend-react/issues/1105)

**Comment by mimarz** [comment] 2023-10-31 13:28
Duplicate of #725

**Closed by mimarz** 2023-10-31 13:28 UTC
Labels: component, 🎨 figma
